#!name=移除知乎广告 by fengxu
#!desc=规则移除了知乎首屏广告、答案列表广告、答案详情底部广告、答案详情底部的推荐词

[URL Rewrite]
# 知乎问题相关搜索关键词
https:\/\/(www|zhuanlan).zhihu.com\/api\/v4\/search\/related_queries\/answer\/\w+ - reject
# 知乎答案广告
https:\/\/(www|zhuanlan).zhihu.com\/api\/v\d+/answers/\w+/recommendations - reject 
# 知乎预加载开屏广告
https:\/\/api.zhihu.com\/commercial_api\/real_time_launch_v2 - reject
# 知乎预加载开屏广告
https:\/\/api.zhihu.com\/commercial_api\/launch_v2 - reject
# 知乎视频广告
https:\/\/lens.zhihu.com\/api\/v\d+\/videos\/\w+ - reject
# 知乎视频广告
https:\/\/vdn\d*.vzuu.com\/[H|S]D\/.* - reject 
https:\/\/www.zhihu.com\/api\/v\d+\/answers\/\w+\/recommendations.*?load_new_ad.* - reject
# 知乎vip弹框
^https:\/\/api\.zhihu\.com\/bazaar\/vip_tab\/header\?downgradable=\d*&user_mode=full$ - reject

[MITM]
hostname = %APPEND% *.vzuu.com, api.zhihu.com, zhuanlan.zhihu.com, www.zhihu.com, lens.zhihu.com

[Script]
知乎答案列表广告 = type=http-response,pattern=https:\/\/api.zhihu.com\/questions\/\w+/feeds,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/fengxuway/surge_rule_for_clean_ad/main/zhihu_list_feed_ad.js,script-update-interval=0

